spring:
  mail:
    host: smtp.163.com
    username: renai_2568092604@163.com
    password: TREMMSLQFSOYKZUU
  rabbitmq:
    addresses: localhost
    username: guest
    password: guest
    virtual-host: /
  security:
    filter:
      order: -100
    jwt:
      key: renaiskey
      expire: 7
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testdatabase
    username: root
    password: root
